// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OWCodigo5.Data;

#nullable disable

namespace OWCodigo5.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240703083320_Fixedsientos")]
    partial class Fixedsientos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OWCodigo5.Models.Actor", b =>
                {
                    b.Property<int>("IdActor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdActor"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("IdObra")
                        .HasColumnType("int");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Personaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RolEspecifico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdActor");

                    b.HasIndex("IdObra");

                    b.ToTable("Actores");
                });

            modelBuilder.Entity("OWCodigo5.Models.Asiento", b =>
                {
                    b.Property<int>("IdAsiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsiento"));

                    b.Property<int?>("AsientoIdAsiento")
                        .HasColumnType("int");

                    b.Property<string>("Fila")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("NumeroAsiento")
                        .HasColumnType("int");

                    b.Property<string>("TipoDeAsiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdAsiento");

                    b.HasIndex("AsientoIdAsiento");

                    b.ToTable("Asientos");
                });

            modelBuilder.Entity("OWCodigo5.Models.Carrito", b =>
                {
                    b.Property<int>("IdCarrito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarrito"));

                    b.Property<string>("Fila")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("IdAsiento")
                        .HasColumnType("int");

                    b.Property<int>("IdObraTeatro")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("NumeroAsiento")
                        .HasColumnType("int");

                    b.Property<int>("NumeroTicket")
                        .HasColumnType("int");

                    b.Property<int?>("ObraTeatroIdObraTeatro")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdCarrito");

                    b.HasIndex("IdAsiento");

                    b.HasIndex("IdObraTeatro");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("ObraTeatroIdObraTeatro");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Carritos");
                });

            modelBuilder.Entity("OWCodigo5.Models.Director", b =>
                {
                    b.Property<int>("IdDirector")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDirector"));

                    b.Property<int>("IdObra")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.HasKey("IdDirector");

                    b.HasIndex("IdObra");

                    b.ToTable("Directores");
                });

            modelBuilder.Entity("OWCodigo5.Models.Genero", b =>
                {
                    b.Property<int>("IdGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGenero"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdGenero");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("OWCodigo5.Models.Obra", b =>
                {
                    b.Property<int>("IdObra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdObra"));

                    b.Property<DateTime>("FechaPresentacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdGenero")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdObra");

                    b.HasIndex("IdGenero");

                    b.ToTable("Obras");
                });

            modelBuilder.Entity("OWCodigo5.Models.ObraTeatro", b =>
                {
                    b.Property<int>("IdObraTeatro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdObraTeatro"));

                    b.Property<int>("IdObra")
                        .HasColumnType("int");

                    b.Property<int>("IdTeatro")
                        .HasColumnType("int");

                    b.Property<int?>("ObraIdObra")
                        .HasColumnType("int");

                    b.HasKey("IdObraTeatro");

                    b.HasIndex("IdObra");

                    b.HasIndex("IdTeatro");

                    b.HasIndex("ObraIdObra");

                    b.ToTable("ObrasTeatros");
                });

            modelBuilder.Entity("OWCodigo5.Models.Teatro", b =>
                {
                    b.Property<int>("IdTeatro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTeatro"));

                    b.Property<int>("Localidad")
                        .HasColumnType("int");

                    b.Property<int>("Nombre")
                        .HasMaxLength(255)
                        .HasColumnType("int");

                    b.HasKey("IdTeatro");

                    b.ToTable("Teatros");
                });

            modelBuilder.Entity("OWCodigo5.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<int>("Cedula")
                        .HasColumnType("int");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("OWCodigo5.Models.Actor", b =>
                {
                    b.HasOne("OWCodigo5.Models.Obra", "Obra")
                        .WithMany("Actores")
                        .HasForeignKey("IdObra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("OWCodigo5.Models.Asiento", b =>
                {
                    b.HasOne("OWCodigo5.Models.Asiento", null)
                        .WithMany("Asientos")
                        .HasForeignKey("AsientoIdAsiento");
                });

            modelBuilder.Entity("OWCodigo5.Models.Carrito", b =>
                {
                    b.HasOne("OWCodigo5.Models.Asiento", "Asiento")
                        .WithMany()
                        .HasForeignKey("IdAsiento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OWCodigo5.Models.ObraTeatro", "ObraTeatro")
                        .WithMany()
                        .HasForeignKey("IdObraTeatro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OWCodigo5.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OWCodigo5.Models.ObraTeatro", null)
                        .WithMany("Carritos")
                        .HasForeignKey("ObraTeatroIdObraTeatro");

                    b.HasOne("OWCodigo5.Models.Usuario", null)
                        .WithMany("Carritos")
                        .HasForeignKey("UsuarioIdUsuario");

                    b.Navigation("Asiento");

                    b.Navigation("ObraTeatro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OWCodigo5.Models.Director", b =>
                {
                    b.HasOne("OWCodigo5.Models.Obra", "Obra")
                        .WithMany("Directores")
                        .HasForeignKey("IdObra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("OWCodigo5.Models.Obra", b =>
                {
                    b.HasOne("OWCodigo5.Models.Genero", "Genero")
                        .WithMany("Obras")
                        .HasForeignKey("IdGenero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("OWCodigo5.Models.ObraTeatro", b =>
                {
                    b.HasOne("OWCodigo5.Models.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("IdObra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OWCodigo5.Models.Teatro", "Teatro")
                        .WithMany()
                        .HasForeignKey("IdTeatro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OWCodigo5.Models.Obra", null)
                        .WithMany("ObraTeatros")
                        .HasForeignKey("ObraIdObra");

                    b.Navigation("Obra");

                    b.Navigation("Teatro");
                });

            modelBuilder.Entity("OWCodigo5.Models.Asiento", b =>
                {
                    b.Navigation("Asientos");
                });

            modelBuilder.Entity("OWCodigo5.Models.Genero", b =>
                {
                    b.Navigation("Obras");
                });

            modelBuilder.Entity("OWCodigo5.Models.Obra", b =>
                {
                    b.Navigation("Actores");

                    b.Navigation("Directores");

                    b.Navigation("ObraTeatros");
                });

            modelBuilder.Entity("OWCodigo5.Models.ObraTeatro", b =>
                {
                    b.Navigation("Carritos");
                });

            modelBuilder.Entity("OWCodigo5.Models.Usuario", b =>
                {
                    b.Navigation("Carritos");
                });
#pragma warning restore 612, 618
        }
    }
}
